# Generated by Django 2.0.1 on 2018-01-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beliefs', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='beliefs',
            field=models.ManyToManyField(related_name='topics_for_beliefs', to='beliefs.Belief'),
        ),
    ]
