# Generated by Django 2.0.1 on 2018-01-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propositions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('veracity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propositions', models.ManyToManyField(blank=True, related_name='beliefs_from_proposition', to='propositions.Proposition')),
            ],
            options={
                'db_table': 'beliefs',
                'ordering': ('id',),
            },
        ),
    ]
